/* v2 Phase F: Ready-made ideas library. Stage 3: deeper content.
   Every idea follows the same rules, so there is nothing left to decide
   and the time is never wasted:
   - first: one tiny physical move that takes under a minute.
   - steps: short, concrete, with numbers (reps, minutes, counts).
   - where: a real place.
   - need: things to have ready, and links only to primary sources that
     stay put (RFCs, W3C, MITRE, CISA, the service's own settings page).
   - outcome: what you end with. Every idea leaves something behind: a
     draft, a diagram, a note, a fixed weak spot, a booked plan. "Watch a
     video" is never an idea on its own.
   - size: 15 | 30 | 60 | 120 minutes. tag: one of Backlog's TAGS.
   Work is written for someone who has worked in identity security for
   years and writes about it; it assumes that depth. Learn, Mind, Body,
   Home and Family are for growing as a person, away from work. */

var Starters = (function () {
  var list = [
    /* ----- Work: writing and the craft ----- */
    { what: "Turn one incident into a post", size: 60, tag: "Work",
      first: "Open a note and write one line: the identity incident or near-miss you still think about.",
      steps: ["Strip names. Write the timeline in 5 bullets", "Name the control that failed, and why it looked fine on paper",
        "Write the fix you'd make now: the exact policy, config or process change", "Name the one signal that would have caught it early",
        "Draft 600 words: story, failure, fix, takeaway"],
      where: "Desk, laptop", need: ["Notes app"],
      outcome: "A 600-word first draft built on something only you saw" },
    { what: "Write a contrarian take", size: 30, tag: "Work",
      first: "Write down one identity best practice you only half agree with.",
      steps: ["State the usual view fairly, in 2 sentences", "List 3 real situations where it breaks",
        "Write what you'd do instead, and what it costs", "Write the evidence you have, and what you'd need to be sure",
        "Turn the title into a claim, not a question"],
      where: "Anywhere", need: ["Notes app"],
      outcome: "A titled outline for a post people will argue with" },
    { what: "Draw the flow you explain most", size: 60, tag: "Work",
      first: "Open Excalidraw and draw one box: the user.",
      steps: ["Pick the flow you keep explaining: workforce SSO with conditional access, or customer login with passkeys and fallback",
        "Draw user, device, IdP, app, directory and API as boxes", "Label every arrow with the protocol and the token it carries",
        "Draw the trust boundaries as dashed lines", "Mark in red the 3 places it most often breaks"],
      where: "Desk, laptop", need: ["Excalidraw: https://excalidraw.com"],
      outcome: "One reusable diagram for posts, talks and white papers" },
    { what: "Edit a draft as a hostile CISO", size: 30, tag: "Work",
      first: "Open your latest draft and read the title out loud.",
      steps: ["Underline every claim that has no number, source or story behind it", "Circle every term a busy CISO would skim past",
        "Fix or delete each one", "Cut 20% of the words", "Rewrite the title so it states the takeaway"],
      where: "Desk", need: ["The draft"],
      outcome: "A draft that survives a skeptical reader" },
    { what: "Answer one real question publicly", size: 30, tag: "Work",
      first: "Find one identity question in your comments, DMs or r/cybersecurity that got weak answers.",
      steps: ["Write the direct answer in the first sentence", "Then the why, in 3 short lines", "Then the caveat that experience teaches",
        "Post it, and save it as a seed for a longer piece"],
      where: "Anywhere", need: ["Forum: https://www.reddit.com/r/cybersecurity/"],
      outcome: "One genuinely useful public answer and a post seed" },
    { what: "Plan next month's writing", size: 30, tag: "Work",
      first: "Open your ideas note and copy the best 8 into a list.",
      steps: ["Score each 1-3: do I have a real story?", "Score 1-3: would a practitioner save this?", "Score 1-3: can I draft it in 2 hours?",
        "Keep the top 4 and put each on a date in your calendar", "Write the first line of the first one now"],
      where: "Desk", need: ["Ideas note", "Calendar"],
      outcome: "Four posts on the calendar, one already started" },
    { what: "Capture 10 post ideas from your week", size: 15, tag: "Work",
      first: "Open a note called Ideas.",
      steps: ["3 questions people asked you at work this week", "3 mistakes you watched a team repeat",
        "2 things you changed your mind about this year", "2 how-tos only someone with your years could write", "Star the one you'd read first"],
      where: "Anywhere", need: ["Notes app"],
      outcome: "Ten ideas ranked, with a clear next post" },
    { what: "Write the letter to year-2 you", size: 30, tag: "Work",
      first: "Write: \"If I were starting in identity again, I'd want to know...\"",
      steps: ["List 5 lessons it took you years to learn", "Give each a 2-line story from real work",
        "Cut to the 3 strongest", "Draft it as a post"],
      where: "Anywhere", need: ["Notes app"],
      outcome: "A mentoring post that only you could write" },
    { what: "Draft a LinkedIn post that teaches", size: 30, tag: "Work",
      first: "Write the first line: the mistake, stated plainly.",
      steps: ["Line 2: why smart teams still make it", "Three short lines: what to do instead, with one real example",
        "One line: how to check if you have this problem", "End with one honest question", "Save as a draft. Post tomorrow morning."],
      where: "Desk or sofa", need: ["A starred idea from your Ideas note"],
      outcome: "A post that leaves the reader with a check they can run" },
    { what: "Write a white paper section", size: 120, tag: "Work",
      first: "Write the one sentence the reader should believe at the end.",
      steps: ["Write the problem statement and who it's for, in 5 lines", "Outline 5 sections, one claim each",
        "Draft section 1 in full, 50 minutes, no editing", "Break 10 minutes, away from the screen",
        "Add 2 citations from primary sources: an RFC, NIST, or a real incident report", "Stop mid-sentence so tomorrow is easy to start"],
      where: "Desk, door closed", need: ["Notes app", "Water", "Headphones"],
      outcome: "An outline and one finished section with sources" },
    { what: "Deep work hour", size: 60, tag: "Work",
      first: "Write the one hard task on paper and put it next to the keyboard.",
      steps: ["Phone in another room, notifications off", "Work on only that task for 50 minutes",
        "When you get stuck, write the question down and keep going", "Last 10 minutes: note where you stopped and the next step"],
      where: "Desk, door closed", need: ["Paper and pen", "Water", "Headphones"],
      outcome: "Real progress on the hardest thing, and the next step written down" },
    { what: "Write a talk proposal", size: 60, tag: "Work",
      first: "Write the title as a promise: what the audience will be able to do after.",
      steps: ["Write a 3-sentence abstract: the problem, what you learned the hard way, what they take away",
        "List 3 takeaways, each one a thing to do on Monday", "Write a 2-line speaker bio", "Find one open call for papers and note the deadline"],
      where: "Desk, laptop", need: ["Open calls: https://www.google.com/search?q=identity+security+conference+call+for+papers"],
      outcome: "A proposal ready to submit" },
    { what: "Plan tomorrow's top 3", size: 15, tag: "Work",
      first: "Open tomorrow in your calendar.",
      steps: ["Look at meetings and fixed times", "Write the 3 things that would make tomorrow a good day",
        "Put the hardest one in the first free slot"],
      where: "Anywhere", need: ["Calendar"],
      outcome: "Tomorrow decided before it starts" },

    /* ----- Work: professional study, primary sources with an exercise ----- */
    { what: "Audit against the OAuth security BCP", size: 60, tag: "Work",
      first: "Open RFC 9700 and jump to section 2, Best Practices.",
      steps: ["Read the recommendations for redirect-based flows and token replay", "For every MUST, write yes, no or unsure for one app you know well",
        "Pick the riskiest no and write the fix in one paragraph", "Note one line for a post: the gap most teams have"],
      where: "Desk", need: ["RFC 9700: https://www.rfc-editor.org/rfc/rfc9700"],
      outcome: "A gap list for a real app, and the top fix written" },
    { what: "Understand DPoP well enough to teach it", size: 30, tag: "Work",
      first: "Open RFC 9449 and read the introduction.",
      steps: ["Draw how a DPoP proof binds an access token to a key", "Write the attack it stops: replay of a stolen token",
        "Write what it does not stop: malware on the device itself", "Decide where you would use it and where bearer tokens are fine"],
      where: "Desk", need: ["RFC 9449: https://www.rfc-editor.org/rfc/rfc9449", "Paper and pen"],
      outcome: "A one-diagram explanation you can reuse" },
    { what: "Design identity for an AI agent", size: 60, tag: "Work",
      first: "Write one line: an agent that books meetings by calling your calendar API for a user.",
      steps: ["Read RFC 8693's intro on delegation and impersonation", "Decide which one the agent should use, and why",
        "Sketch the token chain: user, agent, API. Mark scopes and lifetimes", "List 3 ways it goes wrong and the control for each",
        "Save it. This is a timely post."],
      where: "Desk", need: ["RFC 8693: https://www.rfc-editor.org/rfc/rfc8693"],
      outcome: "A delegation design for agents and a post outline" },
    { what: "Break down MFA fatigue", size: 30, tag: "Work",
      first: "Open MITRE ATT&CK technique T1621.",
      steps: ["Read the procedure examples and the detection section", "Write whether your IdP logs would show it, and where",
        "Write one detection rule in plain words: who, how many pushes, what window", "Write the one control that removes the attack: number matching or phishing-resistant MFA"],
      where: "Desk", need: ["T1621: https://attack.mitre.org/techniques/T1621/"],
      outcome: "A detection rule and a control, written down" },
    { what: "Map a real campaign to your controls", size: 60, tag: "Work",
      first: "Open the CISA advisory on Scattered Spider.",
      steps: ["List every identity step they used: help desk calls, SIM swaps, MFA pushes, new devices", "For each, write the control that stops it",
        "Mark which of those your help desk process would fail today", "Write the one process change you'd push for first"],
      where: "Desk", need: ["CISA AA23-320A: https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-320a"],
      outcome: "A control map and one change worth pushing for" },
    { what: "Find the weak link in passkey recovery", size: 30, tag: "Work",
      first: "Open the WebAuthn spec and find Security Considerations.",
      steps: ["Skim the sections on attestation and credential loss", "Write your org's (or bank's) account recovery path step by step",
        "Circle the weakest step. Recovery usually undoes the passkey.", "Write how you'd make that step as strong as the passkey"],
      where: "Desk", need: ["WebAuthn Level 3: https://www.w3.org/TR/webauthn-3/"],
      outcome: "A recovery path with its weak step named and fixed" },
    { what: "Know your numbers from the DBIR", size: 30, tag: "Work",
      first: "Open the latest Verizon DBIR and search for \"credentials\".",
      steps: ["Write 3 numbers on stolen credentials and MFA bypass, with page numbers", "Write the one that surprised you",
        "Draft one line you'd say to a board with that number"],
      where: "Desk", need: ["DBIR: https://www.verizon.com/business/resources/reports/dbir/"],
      outcome: "Three sourced numbers ready to quote" },
    { what: "Sketch real-time session revocation", size: 30, tag: "Work",
      first: "Open the OpenID Shared Signals working group page.",
      steps: ["Read what CAEP events carry", "Sketch how a password reset at the IdP ends a session in a SaaS app within seconds",
        "List which apps in a stack you know could receive it today", "Write what you'd do for the ones that can't"],
      where: "Desk", need: ["Shared Signals: https://openid.net/wg/sharedsignals/"],
      outcome: "A revocation design, and the gaps in a real stack" },
    { what: "Build a tiny identity lab", size: 60, tag: "Work",
      first: "Open a terminal and check Docker runs.",
      steps: ["Start Keycloak in dev mode (guide below)", "Create a realm, a user and a public client with PKCE",
        "Log in, then decode the access token and read every claim", "Turn on OTP for the user and log in again",
        "Note one thing that surprised you. It's a post."],
      where: "Desk, laptop", need: ["Docker", "Keycloak guide: https://www.keycloak.org/getting-started/getting-started-docker"],
      outcome: "Hands-on proof of how the tokens really look" },
    { what: "Explain it simply", size: 30, tag: "Work",
      first: "Write down one concept you use at work but would struggle to explain.",
      steps: ["Explain it in writing as if to a smart 12-year-old", "Circle the parts where you got vague",
        "Look those parts up in the primary source", "Rewrite the explanation. Keep it; it's half a post."],
      where: "Desk", need: ["Paper or notes app"],
      outcome: "A plain-language explanation, gaps closed" },
    { what: "Score your writing against Paul Graham", size: 30, tag: "Work",
      first: "Open \"How to Write Usefully\".",
      steps: ["Read it once", "Note his four tests: correct, new, important, strong", "Score your last post 1-5 on each",
        "Rewrite its first paragraph to raise the lowest score"],
      where: "A quiet chair", need: ["Essay: https://paulgraham.com/useful.html", "Your last post"],
      outcome: "A sharper opening and a test to reuse" },

    /* ----- Learn: growing beyond work ----- */
    { what: "See compounding with your own numbers", size: 30, tag: "Learn",
      first: "Open a spreadsheet and type your current savings in cell A1.",
      steps: ["In A2 type =A1*1.08 and fill down 25 rows: 8% a year for 25 years", "Do the same in column B at 11%",
        "Compare what the last 5 years add with the first 5", "Add one column where you invest a little more every month",
        "Write one money decision this makes obvious"],
      where: "Desk", need: ["A spreadsheet"],
      outcome: "Compounding you can feel, and one money decision" },
    { what: "Prepare for a real negotiation", size: 30, tag: "Learn",
      first: "Write the negotiation you have coming: salary, rent, a big purchase or a contract.",
      steps: ["Write your walk-away point: what you do if there's no deal", "Write your ideal outcome and a realistic one",
        "Write what the other side probably wants most, and what's cheap for you to give", "Write your opening line, word for word",
        "Say it out loud 3 times"],
      where: "Anywhere quiet", need: ["Notes app"],
      outcome: "A negotiation plan and an opening line you've practised" },
    { what: "Learn CPR and the recovery position", size: 30, tag: "Learn",
      first: "Search for your national Red Cross page on CPR steps.",
      steps: ["Read the adult CPR steps twice", "Practise the hand position and the rhythm on a cushion: about 2 pushes a second",
        "Learn the recovery position, and try it with Sowmya", "Save your emergency number and nearest hospital in your phone favourites"],
      where: "Living room", need: ["A cushion", "Your national Red Cross website"],
      outcome: "The steps that could save a life, practised once" },
    { what: "One idea from history", size: 30, tag: "Learn",
      first: "Pick one: the printing press, the Silk Road, the Green Revolution or the invention of zero.",
      steps: ["Read the Wikipedia summary and one section that catches you", "Write 5 sentences on why it still shapes life today",
        "Tell Sowmya over dinner in 2 minutes"],
      where: "A comfortable chair", need: ["Wikipedia: https://en.wikipedia.org"],
      outcome: "A story you can tell, and understand" },
    { what: "Understand one thing you use every day", size: 30, tag: "Learn",
      first: "Write one question: how does GPS know where I am? How do vaccines train the body? Why do planes stay up?",
      steps: ["Read one good explainer on it", "Draw it as a simple sketch", "Explain it out loud in 2 minutes without notes",
        "Look up the part you stumbled on"],
      where: "Desk or sofa", need: ["Paper and pen"],
      outcome: "Something ordinary that you now truly understand" },
    { what: "20 words in a new language", size: 15, tag: "Learn",
      first: "Pick the language: one for a trip, for family, or just for joy.",
      steps: ["Write 20 words for things in the room you're in", "Look each up and say it out loud 3 times",
        "Stick 5 of them on the real objects", "Test yourself tomorrow morning"],
      where: "Any room at home", need: ["Phone translator", "Sticky notes"],
      outcome: "20 words and a quiz waiting for tomorrow" },
    { what: "Speak for 2 minutes, then do it better", size: 15, tag: "Learn",
      first: "Prop your phone up and pick a topic you know well.",
      steps: ["Record a 2-minute explanation", "Watch it once and count your filler words", "Note one habit: pace, eye contact or ums",
        "Record again, fixing only that one thing"],
      where: "A quiet room", need: ["Phone"],
      outcome: "A second take that is clearly better than the first" },
    { what: "Learn 3 useful knots", size: 15, tag: "Learn",
      first: "Find a piece of rope, a shoelace or a charging cable.",
      steps: ["Bowline: a loop that won't slip", "Clove hitch: tie to a pole or rail", "Reef knot: join two ends",
        "Tie each 5 times without looking"],
      where: "Anywhere", need: ["Rope or a shoelace", "Guides: https://www.animatedknots.com"],
      outcome: "Three knots you can tie from memory" },
    { what: "Find 3 constellations tonight", size: 30, tag: "Learn",
      first: "Step outside after dark and let your eyes adjust for 5 minutes.",
      steps: ["Open a star chart app and find the brightest star you can see", "Find 3 constellations around it",
        "Learn one story behind one of them", "Show Sowmya"],
      where: "Balcony, terrace or a dark spot", need: ["A free star chart app"],
      outcome: "Three shapes in the sky you'll recognise from now on" },
    { what: "Read a book, 25 minutes", size: 30, tag: "Learn",
      first: "Put the book on your chair now.",
      steps: ["Phone in another room", "Read for 25 minutes", "Write one line about what stayed with you, and one place to use it"],
      where: "Your reading chair", need: ["The book", "A pen"],
      outcome: "One idea carried out of the book" },

    { what: "One real lesson on Khan Academy", size: 60, tag: "Learn",
      first: "Open Khan Academy and pick a unit you never learned properly: economics, personal finance, statistics or biology.",
      steps: ["Watch or read the first lesson, pausing to take notes", "Do every practice question, no skipping",
        "Write the 3 ideas you'd teach someone else", "Put the next lesson in your calendar"],
      where: "Desk", need: ["Khan Academy: https://www.khanacademy.org", "Notebook"],
      outcome: "One lesson finished, with practice, and the next booked" },
    { what: "Museum or library afternoon", size: 120, tag: "Learn",
      first: "Look up the nearest museum or big library and its opening hours.",
      steps: ["Go, ideally with Sowmya", "Pick just 3 objects or books and spend 15 minutes with each",
        "Read everything about each one", "Over tea after, each tell the other the best story you found"],
      where: "A museum or library", need: ["Tickets if needed", "Phone for notes"],
      outcome: "Three stories you didn't know this morning" },

    /* ----- Mind: calm, reflection and making things ----- */
    { what: "10-minute meditation", size: 15, tag: "Mind",
      first: "Sit down, feet flat, and set a 10-minute timer.",
      steps: ["Count breaths from 1 to 10, then start again", "When you lose count, start at 1. That's the practice.",
        "When the timer ends, note roughly how many times you restarted"],
      where: "A chair in a quiet room", need: ["A timer"],
      outcome: "A calmer head and a baseline to compare" },
    { what: "Worry dump", size: 15, tag: "Mind",
      first: "Open a blank page and set a 5-minute timer.",
      steps: ["Write every worry until the timer ends, no editing", "Mark each one: can act on, or can't",
        "For each can-act, write the very next step", "Close the notebook. The rest can wait."],
      where: "Anywhere", need: ["Paper and pen"],
      outcome: "Worries turned into next steps" },
    { what: "Three good things", size: 15, tag: "Mind",
      first: "Write today's date and the number 1.",
      steps: ["Write 3 things that went well today, however small", "For each, write why it happened",
        "Read them back once"],
      where: "Bed or a quiet chair", need: ["Notebook"],
      outcome: "A day remembered for what went right" },
    { what: "Life review, not work", size: 30, tag: "Mind",
      first: "Write 6 words down the page: health, relationships, money, growth, fun, rest.",
      steps: ["Score each from 1 to 10, honestly", "Write one line on why for the lowest two", "Pick one of them",
        "Write one small action for this week and put it in the calendar"],
      where: "A quiet spot", need: ["Notebook", "Calendar"],
      outcome: "The weakest part of life named, and one action booked" },
    { what: "Design your ideal ordinary day", size: 30, tag: "Mind",
      first: "Draw a line down a page: ideal day on the left, today on the right.",
      steps: ["Write your ideal ordinary weekday, hour by hour", "Write what today actually looked like",
        "Circle the biggest gap", "Pick one change to try tomorrow"],
      where: "A quiet spot", need: ["Paper and pen"],
      outcome: "One change toward the day you actually want" },
    { what: "Values check", size: 30, tag: "Mind",
      first: "Write down the 5 things that matter most to you. Don't overthink it.",
      steps: ["For each, write one thing you did this month that matched it", "And one thing that went against it",
        "Pick the value you've neglected most", "Write one way to honour it this week"],
      where: "Somewhere quiet", need: ["Notebook"],
      outcome: "Your values checked against how you actually live" },
    { what: "Draw for 15 minutes", size: 15, tag: "Mind",
      first: "Put a pen, paper and a mug on the table.",
      steps: ["Draw the mug for 5 minutes without lifting the pen", "Draw it again looking more at the mug than the paper",
        "Draw it a third time, adding the shadows"],
      where: "Table", need: ["Pen", "Paper", "A mug"],
      outcome: "Three drawings, each better than the last" },
    { what: "Write a 100-word story", size: 15, tag: "Mind",
      first: "Write one opening line about something you saw today.",
      steps: ["Tell a whole story in exactly 100 words", "Give it a beginning, a turn and an end", "Cut every word that isn't needed",
        "Read it aloud to Sowmya"],
      where: "Anywhere", need: ["Notes app"],
      outcome: "A finished tiny story" },
    { what: "Read one poem out loud", size: 15, tag: "Mind",
      first: "Open the Poetry Foundation's poem of the day.",
      steps: ["Read it out loud slowly", "Read it again and mark the line that stays with you", "Write that line in your notebook"],
      where: "A quiet chair", need: ["Poetry Foundation: https://www.poetryfoundation.org"],
      outcome: "One line worth keeping" },
    { what: "Photo walk", size: 30, tag: "Mind",
      first: "Step outside with your phone camera open.",
      steps: ["Walk 15 minutes out, 15 back", "Take 10 photos of one theme: doors, shadows, signs or green",
        "Keep the best 3, delete the rest"], where: "Your neighbourhood", need: ["Shoes", "Phone"],
      outcome: "Three photos and a slower way of seeing" },
    { what: "Journal one page", size: 15, tag: "Mind",
      first: "Write today's date at the top of a page.",
      steps: ["What took my energy this week?", "What gave me energy?", "One thing I'll do differently next week"],
      where: "A quiet spot", need: ["Notebook and pen"],
      outcome: "One change for next week" },

    { what: "Plan the next 90 days", size: 60, tag: "Mind",
      first: "Write the date 90 days from today at the top of a page.",
      steps: ["Write what you want to be true by then in health, relationships, growth and fun", "Keep only the 3 that matter most",
        "For each, write what done looks like, in one line", "Break each into 3 monthly steps", "Put the first step of each in this week's calendar"],
      where: "A quiet spot, ideally a cafe", need: ["Notebook", "Calendar"],
      outcome: "Three 90-day goals with the first steps booked" },

    /* ----- Body: structured, with numbers to beat ----- */
    { what: "Strength: 4 moves, 3 rounds", size: 30, tag: "Body",
      first: "Clear a mat-sized spot and put a chair beside it.",
      steps: ["Split squats, 8 each leg (hold the chair)", "Push-ups, as many as you can minus 2", "Single-leg hip hinge, 8 each leg",
        "Plank, 40 seconds", "Rest 90 seconds, then repeat. 3 rounds", "Write down your reps"],
      where: "Living room floor", need: ["A chair", "A mat or towel"],
      outcome: "Your numbers to beat next time" },
    { what: "Desk-body reset", size: 15, tag: "Body",
      first: "Stand up and put both hands on the back of your chair.",
      steps: ["Chin tucks, 10 slow", "Upper back over the chair back, 10 extensions", "Hip flexor stretch, 45 seconds each side",
        "Glute bridges, 20", "Wall angels, 10"],
      where: "Next to your desk", need: ["A chair", "A wall"],
      outcome: "Neck, back and hips undone from sitting" },
    { what: "Zone 2 walk-run", size: 30, tag: "Body",
      first: "Change into shoes you can run in.",
      steps: ["Walk briskly 5 minutes", "Then jog slowly enough that you can speak in full sentences", "Walk whenever you can't. 20 minutes total",
        "Walk 5 minutes to cool down", "Note how far you got"],
      where: "A loop from your door", need: ["Running shoes", "Water for after"],
      outcome: "An easy aerobic session and a distance to compare" },
    { what: "Walk and think", size: 30, tag: "Body",
      first: "Write one question you're stuck on, then step outside.",
      steps: ["Walk 12 minutes out thinking only about that question", "Turn back", "On the way back, say your answer into a voice note"],
      where: "Outside, any quiet route", need: ["Shoes", "Phone for the voice note"],
      outcome: "A walk, and an answer to something that was stuck" },
    { what: "10-minute walk", size: 15, tag: "Body",
      first: "Put on your shoes and step outside.",
      steps: ["Walk one way for 5 minutes", "Turn around and walk back", "Phone stays in your pocket"],
      where: "Outside, any direction", need: ["Shoes", "Keys"],
      outcome: "A clear head and 1,000 steps" },
    { what: "Stair intervals", size: 15, tag: "Body",
      first: "Walk to the nearest staircase.",
      steps: ["Easy up and down, 3 times", "Brisk up, easy down, 5 times, hand on the rail", "Rest 1 minute", "5 more brisk"],
      where: "Stairs in your building", need: ["Shoes", "Water"],
      outcome: "Heart rate up in a quarter of an hour" },
    { what: "Easy yoga flow", size: 30, tag: "Body",
      first: "Roll out a mat or a towel.",
      steps: ["Cat-cow, 10 slow rounds", "Downward dog, 5 breaths", "Low lunge, 5 breaths each side",
        "Warrior 2, 5 breaths each side", "Seated forward fold, 1 minute", "Lie flat, eyes closed, 3 minutes"],
      where: "Living room floor", need: ["Mat or towel"],
      outcome: "Loose hips and a calmer head" },
    { what: "Breathing reset", size: 15, tag: "Body",
      first: "Put the phone face down and sit up straight.",
      steps: ["Box breathing: in 4, hold 4, out 4, hold 4", "Do it for 5 minutes", "Then walk slowly for 5 minutes", "Drink a glass of water"],
      where: "A chair, then a short walk", need: ["Nothing"],
      outcome: "Out of the scroll, back in your body" },
    { what: "Bike ride", size: 60, tag: "Body",
      first: "Pump the tyres and fill a water bottle.",
      steps: ["Ride out easy for 10 minutes", "Ride 30 minutes at a pace that makes talking hard", "Ride home easy",
        "Stretch quads and hips for 5 minutes"],
      where: "A loop with few junctions", need: ["Bike", "Helmet", "Water", "Lights if it's getting dark"],
      outcome: "A proper cardio session" },
    { what: "Long walk or hike", size: 120, tag: "Body",
      first: "Pick the route on the map and fill a water bottle.",
      steps: ["Tell someone your route", "Walk out for 50 minutes", "Stop for a snack and a view", "Walk back"],
      where: "A trail, park or long road with a footpath", need: ["Good shoes", "Water", "A snack", "Charged phone"],
      outcome: "Two hours outside and 10,000 steps" },

    { what: "Set up a week of better sleep", size: 15, tag: "Body",
      first: "Set one wake-up time for all 7 days, weekends included.",
      steps: ["Set a caffeine cutoff: none after 2 pm", "Set a phone alarm 45 minutes before bed that means screens off",
        "Put the phone charger outside the bedroom", "Go outside for 10 minutes of daylight within an hour of waking"],
      where: "Bedroom", need: ["Phone alarms", "A charger in another room"],
      outcome: "A sleep plan that starts tonight" },

    /* ----- Home ----- */
    { what: "Learn one dish properly", size: 60, tag: "Home",
      first: "Pick one dish you eat often but have never made well, and read one recipe for it end to end.",
      steps: ["Prep everything before the heat goes on", "Cook it exactly as written, no changes",
        "Taste at each step and note what changes", "Write what you'd change next time"],
      where: "Kitchen", need: ["The ingredients", "One trusted recipe"],
      outcome: "A dish you can make again, with your own notes" },
    { what: "Batch cook lunches", size: 60, tag: "Home",
      first: "Put a pot of water or rice on to boil.",
      steps: ["One grain: rice, quinoa or pasta", "One protein: dal, eggs, chicken or tofu", "One tray of roasted vegetables",
        "Split into 3 containers", "Clean as you go"], where: "Kitchen", need: ["3 containers", "A tray", "A big pot"],
      outcome: "Three lunches done" },
    { what: "15-minute room reset", size: 15, tag: "Home",
      first: "Start a 15-minute timer and put on one song you like.",
      steps: ["Rubbish out", "Dishes to the sink or dishwasher", "Clothes to the basket", "Cushions and surfaces straight", "Stop when the timer ends"],
      where: "The room you spend most time in", need: ["A bag", "A timer"],
      outcome: "One calm room" },
    { what: "Fix one small thing", size: 30, tag: "Home",
      first: "Walk through the house and list 3 small broken things.",
      steps: ["Pick the easiest one", "Get the tool before you start", "Fix it", "Put the tool back"],
      where: "Around the house", need: ["Screwdriver set", "Tape, glue or batteries, depending"],
      outcome: "One annoyance gone for good" },
    { what: "Plan meals and a shopping list", size: 30, tag: "Home",
      first: "Open the fridge and write what needs using up.",
      steps: ["Pick 4 dinners for the week, one using those leftovers", "Write the list grouped by aisle",
        "Order online or put it on the fridge"], where: "Kitchen", need: ["Notes app or paper"],
      outcome: "A week of dinners decided" },
    { what: "Kitchen deep clean", size: 60, tag: "Home",
      first: "Empty the sink and run hot water.",
      steps: ["Fridge: bin anything old, wipe the shelves", "Hob and oven top", "Microwave inside", "Counters and backsplash", "Floor last"],
      where: "Kitchen", need: ["Cleaning spray", "Cloths", "Bin bag"],
      outcome: "A kitchen you want to cook in" },
    { what: "10 clothes to donate", size: 30, tag: "Home",
      first: "Open the wardrobe and grab a bag.",
      steps: ["Pull anything you haven't worn in a year", "Keep going until there are 10", "Tie the bag and put it by the door",
        "Put the drop-off in your calendar"], where: "Bedroom", need: ["A big bag"],
      outcome: "Space in the wardrobe and a bag out the door" },
    { what: "Sort the storeroom", size: 120, tag: "Home",
      first: "Put three bags at the door: keep, donate, bin.",
      steps: ["Empty one shelf at a time", "Every item goes in a bag", "Wipe the shelf", "Put back only keep",
        "Donate bag into the car, bin bag out, today"], where: "Storeroom, garage or loft", need: ["3 bags", "Cloth", "Labels"],
      outcome: "A storeroom you can find things in" },

    { what: "Grow something", size: 30, tag: "Home",
      first: "Pick a sunny windowsill and clear it.",
      steps: ["Get one pot, potting soil and seeds or a small plant: basil, mint or coriander", "Plant it and water it well",
        "Set a watering reminder every 2 days", "Take a photo today to compare in a month"],
      where: "Windowsill or balcony", need: ["A pot", "Soil", "Seeds or a small herb plant"],
      outcome: "Something alive you'll cook with" },

    /* ----- Family: time that means something ----- */
    { what: "Weekly check-in together", size: 30, tag: "Family",
      first: "Ask Sowmya: \"Tea and a check-in, 20 minutes?\"",
      steps: ["Each answer: what went well this week?", "What was hard?", "What do you need from me next week?",
        "One thing to look forward to", "Write the answers in a shared note"],
      where: "Sofa, phones away", need: ["Tea", "A shared note"],
      outcome: "Both of you heard, and next week a little easier" },
    { what: "Plan a real date", size: 30, tag: "Family",
      first: "Open both calendars and find one free evening in the next 2 weeks.",
      steps: ["Each suggest one place neither of you has been", "Pick one", "Book it now", "Put it in both calendars"],
      where: "Anywhere", need: ["Calendars", "Phone"],
      outcome: "A date booked, not just talked about" },
    { what: "Write a letter to us, a year from now", size: 30, tag: "Family",
      first: "Write the date one year from today at the top of a page.",
      steps: ["What we're proud of this year", "What we hope is different by then", "One thing we want to have done together",
        "Seal it and put a reminder in the calendar for next year"],
      where: "A quiet spot, together or alone", need: ["Paper and an envelope"],
      outcome: "A letter to open next year" },
    { what: "Record a family story", size: 30, tag: "Family",
      first: "Ask a parent or grandparent: \"What was your first job?\"",
      steps: ["Record the answer on your phone, with permission", "Ask two follow-up questions",
        "Write it up in a shared note", "Add a photo if there is one"],
      where: "In person or on a call", need: ["Phone"],
      outcome: "A story saved before it's forgotten" },
    { what: "Video call the parents", size: 30, tag: "Family",
      first: "Send a message: \"Free for a video call in 10 minutes?\"",
      steps: ["Ask what they did this week", "Show them one thing from your week", "Put the next call in the calendar"],
      where: "Somewhere with good light", need: ["Phone", "Charger"],
      outcome: "A proper catch-up and the next one booked" },
    { what: "Call someone you miss", size: 15, tag: "Family",
      first: "Open your recent calls and find someone you haven't spoken to in a month.",
      steps: ["Call. No answer? Send a voice note", "Ask one real question about their week"],
      where: "Even better on a walk", need: ["Phone"],
      outcome: "One friendship kept warm" },
    { what: "Cook together", size: 60, tag: "Family",
      first: "Pick one recipe neither of you has made.",
      steps: ["Split the jobs: one chops, one cooks", "Music on", "Eat at the table, not in front of a screen"],
      where: "Kitchen", need: ["The ingredients"],
      outcome: "A new dish and an evening together" },
    { what: "Plan a trip", size: 60, tag: "Family",
      first: "Open both calendars and find 3 free days.",
      steps: ["Each name one place", "Check travel time and a rough budget for both", "Pick one together",
        "Book the hardest part now: travel or stay"], where: "Sofa, together", need: ["Calendars", "Laptop"],
      outcome: "A trip with the hard part booked" },
    { what: "Screen-free evening", size: 120, tag: "Family",
      first: "Put both phones in a drawer in another room.",
      steps: ["Cook or order something good", "Eat at the table", "Walk, play a game or read side by side", "Phones back only after 2 hours"],
      where: "Home", need: ["A drawer", "A game or books"],
      outcome: "Two hours fully together" },
    { what: "Write a thank-you message", size: 15, tag: "Family",
      first: "Think of one person who helped you this year and open a chat with them.",
      steps: ["Say what they did", "Say what it changed for you", "Send it. No need for a reply."],
      where: "Anywhere", need: ["Phone"],
      outcome: "Someone's day made" },

    { what: "Host friends for dinner", size: 30, tag: "Family",
      first: "Text 2 couples you like: \"Dinner at ours on <date>?\"",
      steps: ["Pick a menu you can make without stress", "Write the shopping list", "Put the date in both calendars",
        "Plan one question to get everyone talking"],
      where: "Anywhere", need: ["Phone", "Calendar"],
      outcome: "A dinner invited and planned" },
    { what: "Give 2 hours back", size: 30, tag: "Family",
      first: "Search for volunteer opportunities near you this month.",
      steps: ["Pick one that fits a weekend morning", "Sign up now, for both of you if Sowmya's in",
        "Put it in the calendar", "Tell one friend. It makes you more likely to go."],
      where: "Anywhere", need: ["Phone"],
      outcome: "A volunteering slot booked" },

    /* ----- Admin: your own security, done properly ----- */
    { what: "Build the family recovery kit", size: 60, tag: "Admin",
      first: "List the 6 accounts that would hurt most to lose: email, bank, phone carrier, Apple or Google, password manager, work.",
      steps: ["For each, check the recovery email and phone are current", "Save or print backup codes and store them somewhere safe offline",
        "Ask your carrier for a port-out PIN, so a SIM swap needs more than a phone call", "Do the same for Sowmya's accounts, together"],
      where: "Desk, together", need: ["Password manager", "Printer or a safe place for codes"],
      outcome: "Both of you recoverable, and SIM swaps much harder" },
    { what: "Passkeys on the accounts that matter", size: 30, tag: "Admin",
      first: "Open your Google account's passkeys page.",
      steps: ["Add a passkey for Google, Apple and Microsoft", "Add one for your bank and GitHub where offered",
        "Keep one strong backup method for each", "Remove SMS as a sign-in method where the service allows"],
      where: "Desk, with your phone", need: ["Google passkeys: https://myaccount.google.com/signinoptions/passkeys"],
      outcome: "Phishing-resistant sign-in where it counts" },
    { what: "Check who's signed in as you", size: 15, tag: "Admin",
      first: "Open your Google device activity page.",
      steps: ["Sign out any device you don't recognise", "Do the same for your Apple ID devices", "Check WhatsApp linked devices",
        "Change the password if anything was unknown"],
      where: "Anywhere", need: ["Google devices: https://myaccount.google.com/device-activity", "Phone"],
      outcome: "Every signed-in device is one you know" },
    { what: "Delete 5 old accounts", size: 30, tag: "Admin",
      first: "Open your password manager and sort by oldest.",
      steps: ["Find 5 accounts you don't use anymore", "Log in and delete each account, not just the app",
        "Remove them from the password manager", "Every account you close is one less to leak"],
      where: "Desk, laptop", need: ["Password manager"],
      outcome: "A smaller attack surface" },
    { what: "Set up emergency access", size: 30, tag: "Admin",
      first: "Open your password manager's settings and find emergency access.",
      steps: ["Add Sowmya as your emergency contact", "Set up Google's Inactive Account Manager",
        "Write down where the important documents are and share it with her"],
      where: "Desk, laptop", need: ["Password manager", "Inactive Account Manager: https://myaccount.google.com/inactive"],
      outcome: "Your digital life reachable by her if it's ever needed" },
    { what: "Personal security checkup", size: 30, tag: "Admin",
      first: "Open your password manager and look for its security or breach report.",
      steps: ["Change any password it flags as reused or breached", "Check your email on Have I Been Pwned",
        "Run the Google security checkup"],
      where: "Desk, laptop", need: ["Breach check: https://haveibeenpwned.com", "Google checkup: https://myaccount.google.com/security-checkup"],
      outcome: "Reused and breached passwords gone" },
    { what: "Monthly money check", size: 30, tag: "Admin",
      first: "Open last month's bank and card statements.",
      steps: ["Add up spend in 5 buckets: home, food, travel, fun, other", "Circle the biggest surprise",
        "Pick one change for this month", "Move savings now if it's payday"],
      where: "Desk", need: ["Banking app", "A spreadsheet or notes app"],
      outcome: "Where the money went, and one change" },
    { what: "Cancel one subscription", size: 15, tag: "Admin",
      first: "Search your email for \"receipt\" or \"subscription\".",
      steps: ["List every recurring charge", "Mark the ones you haven't used this month", "Cancel one now"],
      where: "Anywhere", need: ["Email", "Banking app"],
      outcome: "Money back every month" },
    { what: "Tax papers in one folder", size: 60, tag: "Admin",
      first: "Make a folder named Tax and the year.",
      steps: ["Save salary slips and certificates", "Save investment and insurance proofs", "Save rent or loan papers",
        "List what's missing and who to ask"], where: "Desk, laptop", need: ["Email", "Cloud folder"],
      outcome: "Tax season half done" },
    { what: "Back up your photos", size: 30, tag: "Admin",
      first: "Plug in the external drive or open your cloud photos.",
      steps: ["Check the phone is backing up and when it last did", "Copy this year's photos to a second place",
        "Put a yearly reminder in the calendar"], where: "Desk", need: ["External drive or cloud storage"],
      outcome: "Photos safe in two places" },
    { what: "Digital declutter afternoon", size: 120, tag: "Admin",
      first: "Make a list: email, photos, files, apps, accounts.",
      steps: ["Unsubscribe from 20 newsletters", "Empty downloads and desktop", "Delete old files in cloud storage",
        "Remove unused browser extensions", "Sign out of devices you don't use"],
      where: "Desk, laptop", need: ["Laptop", "Phone"],
      outcome: "A lighter, safer digital life" },
    { what: "Inbox down to 10", size: 30, tag: "Admin",
      first: "Open your inbox and sort by oldest.",
      steps: ["Archive anything you won't act on", "Reply now to anything under 2 minutes",
        "Move the rest to one follow-up folder", "Stop at 10 left"],
      where: "Desk, laptop", need: ["Email"],
      outcome: "An inbox you can see the bottom of" }
  ];

  // Stable key for Not now and "already added" checks.
  function key(st) { return "s:" + st.what.toLowerCase(); }

  return { list: list, key: key };
})();
