/* v2 Phase F: Ready-made ideas library.
   Every idea follows the same rules, so there is nothing left to decide:
   - first: one tiny physical move that takes under a minute.
   - steps: short, concrete, with numbers (reps, minutes, counts).
   - where: a real place, not "anywhere" unless it truly is.
   - need: things to have ready, and links only to pages that stay put.
   - size: 15 | 30 | 60 | 120 minutes. tag: one of Backlog's TAGS.
   Backlog uses these in the "Ready-made ideas" sheet and in "Just pick
   one for me" when your own list has nothing that fits. */

var Starters = (function () {
  var list = [
    /* ----- Body ----- */
    { what: "10-minute walk", size: 15, tag: "Body",
      first: "Put on your shoes and step outside.",
      steps: ["Walk one way for 5 minutes.", "Turn around and walk back.", "Phone stays in your pocket."],
      where: "Outside, any direction.", need: ["Shoes", "Keys"] },
    { what: "Bodyweight circuit", size: 15, tag: "Body",
      first: "Clear a mat-sized spot on the floor.",
      steps: ["10 squats", "10 push-ups (knees down is fine)", "30-second plank", "Rest 1 minute", "Do 3 rounds"],
      where: "Living room floor", need: ["Nothing. A mat if you have one."] },
    { what: "Stretch reset", size: 15, tag: "Body",
      first: "Stand up and roll your shoulders 10 times.",
      steps: ["Neck: slow circles, 30 seconds each way", "Chest: hands on a door frame, lean in, 30 seconds",
        "Hamstrings: reach for your toes, 1 minute", "Hips: lunge stretch, 1 minute each side", "Back: child's pose, 1 minute"],
      where: "Anywhere with floor space", need: ["Nothing"] },
    { what: "Stair climb", size: 15, tag: "Body",
      first: "Walk to the nearest staircase.",
      steps: ["Walk up and down at an easy pace, 3 times", "Then 5 times at a brisk pace, hand on the rail",
        "Rest 1 minute at the bottom", "Repeat the brisk 5 once more"],
      where: "Stairs in your building", need: ["Shoes", "Water"] },
    { what: "Breathing reset", size: 15, tag: "Body",
      first: "Put the phone face down and sit up straight.",
      steps: ["Box breathing: in 4, hold 4, out 4, hold 4", "Do it for 5 minutes",
        "Then stand and walk slowly for 5 minutes", "Drink a glass of water"],
      where: "A chair, then a short walk", need: ["Nothing"] },
    { what: "20-minute walk-run", size: 30, tag: "Body",
      first: "Change into shoes you can run in.",
      steps: ["Walk briskly for 5 minutes", "Run 1 minute, walk 2 minutes. Do this 4 times", "Walk 3 minutes to cool down"],
      where: "A loop from your door", need: ["Running shoes", "Water for after"] },
    { what: "Easy yoga flow", size: 30, tag: "Body",
      first: "Roll out a mat or a towel.",
      steps: ["Cat-cow, 10 slow rounds", "Downward dog, 5 breaths", "Low lunge, 5 breaths each side",
        "Warrior 2, 5 breaths each side", "Seated forward fold, 1 minute", "Lie flat, eyes closed, 3 minutes"],
      where: "Living room floor", need: ["Mat or towel",
        "Follow-along videos: https://www.youtube.com/results?search_query=20+minute+beginner+yoga"] },
    { what: "Podcast walk", size: 60, tag: "Body",
      first: "Download one podcast episode now, before you leave.",
      steps: ["Walk out for 25 minutes at a pace where you can still talk", "Turn back", "Note one idea from the episode when home"],
      where: "A long loop or a park", need: ["Shoes", "Headphones", "One episode, downloaded"] },
    { what: "Long walk or hike", size: 120, tag: "Body",
      first: "Pick the route on the map and fill a water bottle.",
      steps: ["Tell someone your route", "Walk out for 50 minutes", "Stop for a snack and a view", "Walk back"],
      where: "A trail, park or long road with a footpath", need: ["Good shoes", "Water", "A snack", "Charged phone",
        "Nearby trails: https://www.google.com/maps/search/walking+trails"] },

    { what: "Core 10", size: 15, tag: "Body",
      first: "Lie on your back on the floor.",
      steps: ["Dead bugs, 10 each side", "Bird dogs, 10 each side", "Side plank, 20 seconds each side",
        "Glute bridges, 15", "Do 2 rounds"],
      where: "Floor, on a mat or rug", need: ["Mat or towel"] },
    { what: "Dance it out", size: 15, tag: "Body",
      first: "Put on the first song that makes you want to move.",
      steps: ["4 songs back to back", "No sitting down between songs", "Drink a glass of water after"],
      where: "Living room, curtains optional", need: ["Speaker or headphones"] },
    { what: "Skipping rope", size: 15, tag: "Body",
      first: "Take the rope outside or to a room with a high ceiling.",
      steps: ["Skip 30 seconds, rest 30 seconds", "Do 10 rounds", "Calf stretch against a wall, 30 seconds each side"],
      where: "Balcony, terrace or driveway", need: ["Skipping rope", "Shoes"] },
    { what: "Photo walk", size: 30, tag: "Body",
      first: "Step outside with your phone camera open.",
      steps: ["Walk 15 minutes out, 15 back", "Take 10 photos of one theme: doors, shadows, signs or green",
        "Keep the best 3, delete the rest"], where: "Your neighbourhood", need: ["Shoes", "Phone"] },
    { what: "Bike ride", size: 60, tag: "Body",
      first: "Pump the tyres and fill a water bottle.",
      steps: ["Ride out easy for 10 minutes", "Ride 30 minutes at a pace that makes talking hard", "Ride home easy",
        "Stretch quads and hips for 5 minutes"],
      where: "A loop with few junctions", need: ["Bike", "Helmet", "Water", "Lights if it's getting dark"] },

    /* ----- Work ----- */
    { what: "Outline one article", size: 30, tag: "Work",
      first: "Open a blank note and type a working title.",
      steps: ["Write the one sentence you want readers to remember", "Write 5 bullet points that lead to it",
        "Under each bullet, add one real example", "Stop there. Drafting is a separate block."],
      where: "Desk, laptop", need: ["Notes app"] },
    { what: "Plan tomorrow's top 3", size: 15, tag: "Work",
      first: "Open tomorrow in your calendar.",
      steps: ["Look at meetings and fixed times", "Write the 3 things that would make tomorrow a good day",
        "Put the hardest one in the first free slot"],
      where: "Anywhere", need: ["Calendar", "Notes app"] },
    { what: "Capture 10 article ideas", size: 15, tag: "Work",
      first: "Open a note called Ideas.",
      steps: ["Write 3 questions people asked you at work this month", "Write 3 mistakes you see teams repeat",
        "Write 2 things you changed your mind about", "Write 2 how-tos only you could write", "Star the one you'd read first"],
      where: "Anywhere", need: ["Notes app"] },
    { what: "Draft a LinkedIn post", size: 30, tag: "Work",
      first: "Write the first line: one sharp sentence that states the problem.",
      steps: ["Paragraph 1: what you saw happen", "Paragraph 2: why it matters", "Paragraph 3: what to do instead",
        "End with one honest question", "Save as a draft. Post it tomorrow morning."],
      where: "Desk or sofa", need: ["Notes app or LinkedIn draft", "One star from your Ideas note"] },
    { what: "Edit one draft", size: 30, tag: "Work",
      first: "Open the draft and read the first paragraph out loud.",
      steps: ["Read the whole thing out loud once", "Cut 20%: repeats, warm-up sentences, hedges",
        "Make the title say the takeaway", "Check every paragraph has one idea"],
      where: "Desk, laptop", need: ["The draft"] },
    { what: "Weekly review", size: 30, tag: "Work",
      first: "Open last week in your calendar.",
      steps: ["Write down anything you promised someone", "Clear the desktop and downloads folder",
        "List open loops and pick next steps for each", "Block time next week for the top 2"],
      where: "Desk, laptop", need: ["Calendar", "Task list"] },
    { what: "Add wins to your profile", size: 30, tag: "Work",
      first: "Open a note and write: This quarter I...",
      steps: ["List 3 things you shipped, fixed or led", "Add a number to each: time, risk, money, people",
        "Update your CV with the best one", "Update your LinkedIn headline or About if it's out of date"],
      where: "Desk, laptop", need: ["CV file", "Your LinkedIn profile"] },
    { what: "Write a full first draft", size: 120, tag: "Work",
      first: "Open your outline and turn off notifications.",
      steps: ["Write straight through for 50 minutes. No editing, no research.",
        "Mark gaps with [TK] and keep going", "Break for 10 minutes, away from the screen",
        "Write 40 more minutes", "Stop mid-sentence so tomorrow is easy to start"],
      where: "Desk, door closed", need: ["The outline", "Water", "Headphones"] },

    { what: "Deep work hour", size: 60, tag: "Work",
      first: "Write the one hard task on a piece of paper and put it next to the keyboard.",
      steps: ["Phone in another room, notifications off", "Work on only that task for 50 minutes",
        "When you get stuck, write the question down and keep going", "Last 10 minutes: note where you stopped and the next step"],
      where: "Desk, door closed", need: ["Paper and pen", "Water", "Headphones"] },
    { what: "Turn one article into 5 posts", size: 30, tag: "Work",
      first: "Open your best published article.",
      steps: ["Copy out the 5 strongest sentences", "Turn each into a short post: the point, one example, one question",
        "Schedule or save them one week apart"], where: "Desk", need: ["The article", "Notes app"] },
    { what: "Record a 2-minute tip", size: 30, tag: "Work",
      first: "Write the tip as 3 bullet points on a sticky note.",
      steps: ["Prop the phone at eye level, window in front of you", "Record in one take. Mistakes are fine.",
        "Watch it once. Re-record only if the sound is bad", "Save it with a one-line caption"],
      where: "By a window", need: ["Phone", "Something to prop it on", "Sticky note"] },
    { what: "Message 3 people", size: 15, tag: "Work",
      first: "Open LinkedIn or your contacts and find someone you haven't talked to this year.",
      steps: ["Congratulate one person on news", "Send one person an article they'd like, with a line on why",
        "Ask one person a real question about their work"], where: "Anywhere", need: ["Phone"] },
    { what: "Write a talk proposal", size: 60, tag: "Work",
      first: "Write the title as a promise: what the audience walks away able to do.",
      steps: ["Write a 3-sentence abstract: the problem, what you learned, what they'll take away",
        "List 3 takeaways", "Write a 2-line speaker bio", "Find one conference with an open call and note the deadline"],
      where: "Desk, laptop", need: ["Notes app", "Open calls: https://www.google.com/search?q=identity+security+conference+call+for+papers"] },

    /* ----- Learn ----- */
    { what: "Read and note one article", size: 30, tag: "Learn",
      first: "Open your reading list and pick the oldest saved article.",
      steps: ["Read it once, no notes", "Write 3 takeaways in your own words", "Write one thing you will try or share"],
      where: "A quiet chair", need: ["Reading list", "Notes app"] },
    { what: "Random Wikipedia dive", size: 15, tag: "Learn",
      first: "Tap the link below.",
      steps: ["Read the article that comes up", "Follow one link that looks interesting", "Tell someone one fact you learned today"],
      where: "Anywhere", need: ["Random article: https://en.wikipedia.org/wiki/Special:Random"] },
    { what: "Explain it simply", size: 30, tag: "Learn",
      first: "Write down one concept you use at work but would struggle to explain.",
      steps: ["Explain it in writing as if to a 12-year-old", "Circle the parts where you got vague",
        "Look those parts up", "Rewrite the explanation. Keep it; it's half a blog post."],
      where: "Desk", need: ["Paper or notes app"] },
    { what: "Watch one conference talk", size: 60, tag: "Learn",
      first: "Open the talk search below and pick the first title that makes you curious.",
      steps: ["Watch at 1.25x speed", "Pause and note anything you disagree with", "Write 3 notes and one article idea"],
      where: "Sofa or desk", need: ["Headphones", "Notes app",
        "Identity talks: https://www.youtube.com/results?search_query=Identiverse+talk",
        "Security talks: https://www.youtube.com/results?search_query=RSA+Conference+keynote"] },
    { what: "Read one standard section", size: 30, tag: "Learn",
      first: "Open the search below and pick one section you have never read end to end.",
      steps: ["Read the section once", "Write the 3 requirements that surprised you", "Note one place your team does it differently"],
      where: "Desk", need: ["Notes app", "NIST digital identity guidelines: https://www.google.com/search?q=NIST+SP+800-63"] },
    { what: "Half a course module", size: 120, tag: "Learn",
      first: "Open the course you started and find where you stopped.",
      steps: ["Watch or read for 45 minutes, taking notes", "Break for 10 minutes", "Do the exercise or quiz for 45 minutes",
        "Write what you'll use from it this week"], where: "Desk", need: ["Course login", "Notes app", "Headphones"] },

    { what: "Read a book, 25 minutes", size: 30, tag: "Learn",
      first: "Put the book on your chair now.",
      steps: ["Phone in another room", "Read for 25 minutes", "Write one line about what stayed with you"],
      where: "Your reading chair", need: ["The book", "A pen"] },
    { what: "Learn 5 shortcuts", size: 15, tag: "Learn",
      first: "Open the app you use most at work.",
      steps: ["Look up its keyboard shortcuts", "Pick 5 you'd use daily", "Use each one 5 times now",
        "Write them on a sticky note by the screen"], where: "Desk", need: ["Sticky note"] },
    { what: "Build a tiny identity lab", size: 60, tag: "Learn",
      first: "Open a terminal and check Docker runs.",
      steps: ["Start Keycloak in dev mode with Docker (guide below)", "Create a realm, a user and a client",
        "Log in to the account console as that user", "Turn on OTP for the user and log in again",
        "Note one thing that surprised you. It's a post."],
      where: "Desk, laptop", need: ["Docker",
        "Keycloak guide: https://www.keycloak.org/getting-started/getting-started-docker"] },
    { what: "Sketch one thing", size: 15, tag: "Learn",
      first: "Put a pen and paper on the table next to a mug.",
      steps: ["Draw the mug for 5 minutes without lifting the pen", "Draw it again, looking more at the mug than the paper",
        "Draw it a third time, adding shadows"], where: "Table", need: ["Pen", "Paper", "A mug"] },
    { what: "Journal one page", size: 15, tag: "Learn",
      first: "Write today's date at the top of a page.",
      steps: ["What took my energy this week?", "What gave me energy?", "One thing I'll do differently next week"],
      where: "A quiet spot", need: ["Notebook and pen"] },

    /* ----- Home ----- */
    { what: "Clear one surface", size: 15, tag: "Home",
      first: "Pick the most cluttered table or counter.",
      steps: ["Take everything off", "Wipe it down", "Put back only what belongs there", "The rest goes where it lives, or out"],
      where: "Kitchen counter, desk or table", need: ["A cloth", "A bag for rubbish"] },
    { what: "15-minute room reset", size: 15, tag: "Home",
      first: "Start a 15-minute timer and put on one song you like.",
      steps: ["Rubbish out", "Dishes to the sink or dishwasher", "Clothes to the basket", "Cushions and surfaces straight", "Stop when the timer ends"],
      where: "The room you spend most time in", need: ["A bag", "A timer"] },
    { what: "Empty one drawer", size: 15, tag: "Home",
      first: "Pull out the messiest drawer and tip it onto a towel.",
      steps: ["Bin what's broken or dead", "Move what belongs elsewhere", "Put back only what you use", "Keep like with like"],
      where: "Kitchen or desk drawer", need: ["A towel", "A bag"] },
    { what: "Fix one small thing", size: 30, tag: "Home",
      first: "Walk through the house and list 3 small broken things.",
      steps: ["Pick the easiest one", "Get the tool before you start", "Fix it", "Put the tool back"],
      where: "Around the house", need: ["Screwdriver set", "Tape, glue or batteries, depending"] },
    { what: "Plan meals and a shopping list", size: 30, tag: "Home",
      first: "Open the fridge and write what needs using up.",
      steps: ["Pick 4 dinners for the week, one using those leftovers", "Write the list grouped by aisle",
        "Order online or put it on the fridge"], where: "Kitchen", need: ["Notes app or paper"] },
    { what: "Batch cook lunches", size: 60, tag: "Home",
      first: "Put a pot of water or rice on to boil.",
      steps: ["One grain: rice, quinoa or pasta", "One protein: dal, eggs, chicken or tofu", "One tray of roasted vegetables",
        "Split into 3 containers", "Clean as you go"], where: "Kitchen", need: ["3 containers", "A tray", "A big pot"] },

    { what: "Fold one basket", size: 15, tag: "Home",
      first: "Tip the laundry basket onto the bed.",
      steps: ["Sort by person", "Fold or hang everything", "Put it all away, not on the chair"],
      where: "Bedroom", need: ["Hangers"] },
    { what: "10 clothes to donate", size: 30, tag: "Home",
      first: "Open the wardrobe and grab a bag.",
      steps: ["Pull anything you haven't worn in a year", "Keep going until there are 10", "Tie the bag and put it by the door",
        "Put the donation drop-off in your calendar"], where: "Bedroom", need: ["A big bag"] },
    { what: "Kitchen deep clean", size: 60, tag: "Home",
      first: "Empty the sink and run hot water.",
      steps: ["Fridge: bin anything old, wipe the shelves", "Hob and oven top", "Microwave inside",
        "Counters and backsplash", "Floor last"], where: "Kitchen", need: ["Cleaning spray", "Cloths", "Bin bag"] },
    { what: "Wash the car", size: 60, tag: "Home",
      first: "Fill a bucket with warm water and soap.",
      steps: ["Clear out the rubbish inside", "Vacuum seats and mats", "Wash outside top to bottom",
        "Wipe the windows inside and out"], where: "Driveway or car park", need: ["Bucket", "Sponge", "Vacuum", "Cloths"] },
    { what: "Sort the storeroom", size: 120, tag: "Home",
      first: "Put three bags at the door: keep, donate, bin.",
      steps: ["Empty one shelf at a time", "Every item goes in a bag", "Wipe the shelf", "Put back only keep",
        "Donate bag into the car, bin bag out, today"], where: "Storeroom, garage or loft", need: ["3 bags", "Cloth", "Labels"] },

    /* ----- Family ----- */
    { what: "Call someone you miss", size: 15, tag: "Family",
      first: "Open your recent calls and find someone you haven't spoken to in a month.",
      steps: ["Call. No answer? Send a voice note", "Ask one real question about their week"],
      where: "Even better on a walk", need: ["Phone"] },
    { what: "Walk together", size: 30, tag: "Family",
      first: "Ask: \"Walk in 5 minutes?\"",
      steps: ["No phones out", "Each share one good thing and one hard thing from the week", "Pick the route home together"],
      where: "Around the block or a nearby park", need: ["Shoes", "Keys"] },
    { what: "Plan one weekend thing", size: 15, tag: "Family",
      first: "Open both calendars and find one free half-day.",
      steps: ["Each suggest 2 ideas", "Pick one together", "Put it in both calendars now", "Book anything that needs booking"],
      where: "Sofa, together", need: ["Calendars", "Local ideas: https://www.google.com/search?q=things+to+do+near+me+this+weekend"] },
    { what: "Cook together", size: 60, tag: "Family",
      first: "Pick one recipe neither of you has made.",
      steps: ["Split the jobs: one chops, one cooks", "Music on", "Eat at the table, not in front of a screen"],
      where: "Kitchen", need: ["The ingredients", "Recipe ideas: https://www.google.com/search?q=easy+new+dinner+recipes"] },
    { what: "Write a thank-you message", size: 15, tag: "Family",
      first: "Think of one person who helped you this year and open a chat with them.",
      steps: ["Say what they did", "Say what it changed for you", "Send it. No need for a reply."],
      where: "Anywhere", need: ["Phone"] },
    { what: "Make this month's photo album", size: 30, tag: "Family",
      first: "Open your photos to the start of this month.",
      steps: ["Favourite the best 15", "Delete obvious duplicates as you go", "Put the 15 in a shared album", "Send the album to family"],
      where: "Sofa", need: ["Phone"] },
    { what: "Game night", size: 60, tag: "Family",
      first: "Put the game on the table and the phones in a drawer.",
      steps: ["Pick a quick game first to warm up", "Then one longer game", "Loser picks next week's game"],
      where: "Dining table", need: ["A board or card game", "Snacks"] },

    { what: "Video call the parents", size: 30, tag: "Family",
      first: "Send a message: \"Free for a video call in 10 minutes?\"",
      steps: ["Ask what they did this week", "Show them one thing from your week", "Put the next call in the calendar"],
      where: "Somewhere with good light", need: ["Phone", "Charger"] },
    { what: "Write down a family story", size: 30, tag: "Family",
      first: "Ask a parent or grandparent: \"What was your first job?\"",
      steps: ["Record the answer on your phone, with permission", "Ask two follow-up questions",
        "Write it up in a shared note", "Add a photo if there is one"], where: "In person or on a call", need: ["Phone"] },
    { what: "Plan a trip", size: 60, tag: "Family",
      first: "Open both calendars and find 3 free days.",
      steps: ["Each name one place", "Check travel time and a rough budget for both", "Pick one together",
        "Book the hardest part now: travel or stay"], where: "Sofa, together", need: ["Calendars", "Laptop"] },
    { what: "Date night in", size: 120, tag: "Family",
      first: "Pick a recipe and a film together, right now.",
      steps: ["Cook together", "Phones on silent in another room", "Eat at the table, candle if you have one",
        "Watch the film"], where: "Home", need: ["Ingredients", "A film picked in advance"] },

    /* ----- Admin ----- */
    { what: "Inbox down to 10", size: 30, tag: "Admin",
      first: "Open your inbox and sort by oldest.",
      steps: ["Archive anything you won't act on", "Reply now to anything under 2 minutes",
        "Move the rest to one follow-up folder", "Stop at 10 left"],
      where: "Desk, laptop", need: ["Email"] },
    { what: "Personal security checkup", size: 30, tag: "Admin",
      first: "Open your password manager and look for its security or breach report.",
      steps: ["Change any password it flags as reused or breached", "Check your email on Have I Been Pwned",
        "Turn on passkeys or an authenticator app for one important account", "Run the Google security checkup"],
      where: "Desk, laptop", need: ["Password manager", "Breach check: https://haveibeenpwned.com",
        "Google checkup: https://myaccount.google.com/security-checkup"] },
    { what: "Bills and receipts", size: 30, tag: "Admin",
      first: "Open your banking app.",
      steps: ["List bills due in the next 2 weeks", "Pay anything due within 7 days", "Turn on autopay where it makes sense",
        "File this month's receipts in one folder"], where: "Desk", need: ["Banking app", "A receipts folder"] },
    { what: "Cancel one subscription", size: 15, tag: "Admin",
      first: "Search your email for \"receipt\" or \"subscription\".",
      steps: ["List every recurring charge", "Mark the ones you haven't used this month", "Cancel one now"],
      where: "Anywhere", need: ["Email", "Banking app"] },
    { what: "Clean up your phone", size: 15, tag: "Admin",
      first: "Open your photos and go to Screenshots.",
      steps: ["Delete 50 screenshots", "Remove 5 apps you haven't opened in a month", "Move the 8 apps you use most to the first screen"],
      where: "Anywhere", need: ["Phone"] },
    { what: "Expiry dates in the calendar", size: 30, tag: "Admin",
      first: "Get your passport and driving licence out.",
      steps: ["Add each expiry date to your calendar", "Add a reminder 3 months before each",
        "Do the same for insurance, car service and warranties"], where: "Desk", need: ["Documents", "Calendar"] },
    { what: "Delete 5 old accounts", size: 30, tag: "Admin",
      first: "Open your password manager and sort by oldest.",
      steps: ["Find 5 accounts you don't use anymore", "Log in and delete each account, not just the app",
        "Remove them from the password manager", "Every account you close is one less to leak"],
      where: "Desk, laptop", need: ["Password manager"] },
    { what: "Set up emergency access", size: 30, tag: "Admin",
      first: "Open your password manager's settings and find emergency access.",
      steps: ["Add your partner as an emergency contact", "Set up Google's Inactive Account Manager",
        "Write down where the important documents are and share it with your partner"],
      where: "Desk, laptop", need: ["Password manager", "Inactive Account Manager: https://myaccount.google.com/inactive"] },
    { what: "Back up your photos", size: 30, tag: "Admin",
      first: "Plug in the external drive or open your cloud photos.",
      steps: ["Check the phone is backing up and when it last did", "Copy this year's photos to a second place",
        "Put a yearly reminder in the calendar"], where: "Desk", need: ["External drive or cloud storage", "Phone cable"] },
    { what: "Monthly money check", size: 30, tag: "Admin",
      first: "Open last month's bank and card statements.",
      steps: ["Add up spend by 5 buckets: home, food, travel, fun, other", "Circle the biggest surprise",
        "Pick one change for this month", "Move savings now if it's payday"],
      where: "Desk", need: ["Banking app", "Notes app or a spreadsheet"] },
    { what: "Tax papers in one folder", size: 60, tag: "Admin",
      first: "Make a folder named Tax and the year.",
      steps: ["Save salary slips and certificates", "Save investment and insurance proofs",
        "Save rent or loan papers", "List what's missing and who to ask"],
      where: "Desk, laptop", need: ["Email", "Banking app", "Cloud folder"] },
    { what: "Digital declutter afternoon", size: 120, tag: "Admin",
      first: "Make a list: email, photos, files, apps, accounts.",
      steps: ["Unsubscribe from 20 newsletters", "Empty downloads and desktop", "Delete old files in cloud storage",
        "Remove unused browser extensions", "Log out of devices you don't use in your Google and Apple accounts"],
      where: "Desk, laptop", need: ["Laptop", "Phone"] }
  ];

  // Stable key for Not now and "already added" checks.
  function key(st) { return "s:" + st.what.toLowerCase(); }

  return { list: list, key: key };
})();
